name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instala dependências
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Testes
        run: npm run test:coverage
      - name: Checagem de tipos
        run: npm run type-check
      - name: Build
        run: npm run build 